[2025-07-16T04:06:51.951+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-16T04:06:52.030+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_model_training.train_and_log_model scheduled__2025-07-15T00:00:00+00:00 [queued]>
[2025-07-16T04:06:52.085+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_model_training.train_and_log_model scheduled__2025-07-15T00:00:00+00:00 [queued]>
[2025-07-16T04:06:52.117+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-16T04:06:52.164+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2025-07-15 00:00:00+00:00
[2025-07-16T04:06:52.204+0000] {standard_task_runner.py:63} INFO - Started process 2138 to run task
[2025-07-16T04:06:52.208+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_model_training', 'train_and_log_model', 'scheduled__2025-07-15T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/flight_model_dag.py', '--cfg-path', '/tmp/tmpy36tj_hi']
[2025-07-16T04:06:52.364+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask train_and_log_model
[2025-07-16T04:06:52.565+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_model_training.train_and_log_model scheduled__2025-07-15T00:00:00+00:00 [running]> on host ec77630edb53
[2025-07-16T04:06:52.730+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_model_training' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-15T00:00:00+00:00'
[2025-07-16T04:06:52.755+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-16T04:08:07.328+0000] {logging_mixin.py:188} WARNING - 2025/07/16 04:08:07 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-07-16T04:08:09.804+0000] {logging_mixin.py:188} WARNING - 2025/07/16 04:08:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
[2025-07-16T04:08:17.842+0000] {logging_mixin.py:188} WARNING - 2025/07/16 04:08:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-07-16T04:08:18.916+0000] {logging_mixin.py:188} INFO - üèÉ View run suave-dove-944 at: http://mlflow:5000/#/experiments/474368820096796256/runs/dbc8163ba1394ffca4391154719c8b8e
[2025-07-16T04:08:18.917+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/474368820096796256
[2025-07-16T04:08:19.350+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-16T04:08:19.351+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-16T04:08:19.363+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flight_model_training, task_id=train_and_log_model, run_id=scheduled__2025-07-15T00:00:00+00:00, execution_date=20250715T000000, start_date=20250716T040652, end_date=20250716T040819
[2025-07-16T04:08:19.409+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-16T04:08:19.428+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
