[2025-07-15T20:55:28.437+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-15T20:55:28.463+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_model_training.train_and_log_model manual__2025-07-15T20:55:26.172591+00:00 [queued]>
[2025-07-15T20:55:28.471+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_model_training.train_and_log_model manual__2025-07-15T20:55:26.172591+00:00 [queued]>
[2025-07-15T20:55:28.472+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-15T20:55:28.484+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2025-07-15 20:55:26.172591+00:00
[2025-07-15T20:55:28.493+0000] {standard_task_runner.py:63} INFO - Started process 265 to run task
[2025-07-15T20:55:28.496+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_model_training', 'train_and_log_model', 'manual__2025-07-15T20:55:26.172591+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/flight_model_dag.py', '--cfg-path', '/tmp/tmpui4hw39t']
[2025-07-15T20:55:28.499+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask train_and_log_model
[2025-07-15T20:55:28.555+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_model_training.train_and_log_model manual__2025-07-15T20:55:26.172591+00:00 [running]> on host ec77630edb53
[2025-07-15T20:55:28.639+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_model_training' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-15T20:55:26.172591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-15T20:55:26.172591+00:00'
[2025-07-15T20:55:28.640+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-15T20:56:14.222+0000] {logging_mixin.py:188} WARNING - 2025/07/15 20:56:14 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-07-15T20:56:15.092+0000] {logging_mixin.py:188} WARNING - 2025/07/15 20:56:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
[2025-07-15T20:56:19.720+0000] {logging_mixin.py:188} WARNING - 2025/07/15 20:56:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-07-15T20:56:20.783+0000] {logging_mixin.py:188} INFO - üèÉ View run youthful-pug-481 at: http://mlflow:5000/#/experiments/474368820096796256/runs/8b50e6e1c88c42df8d0d6e19665d7295
[2025-07-15T20:56:20.784+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/474368820096796256
[2025-07-15T20:56:21.267+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-15T20:56:21.269+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-15T20:56:21.276+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flight_model_training, task_id=train_and_log_model, run_id=manual__2025-07-15T20:55:26.172591+00:00, execution_date=20250715T205526, start_date=20250715T205528, end_date=20250715T205621
[2025-07-15T20:56:21.321+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-15T20:56:21.335+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-15T20:56:21.337+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
